version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/encore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/gulp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/snowpack"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vite"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/webpack"
    schedule:
      interval: "weekly"
