name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  NODE: 16.x

jobs:
  lint:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Npm
      run: npm install
    - name: Lint
      run: npm run lint
  build:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: "${{ env.NODE }}"
    - name: Yarn
      run: yarn i-all --frozen-lockfile
    - name: Build
      run: yarn b-all
